// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: pkg/apis/marina.proto

package apis

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MarinaClient is the client API for Marina service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarinaClient interface {
	CreateTerminal(ctx context.Context, in *TerminalCreateRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type marinaClient struct {
	cc grpc.ClientConnInterface
}

func NewMarinaClient(cc grpc.ClientConnInterface) MarinaClient {
	return &marinaClient{cc}
}

func (c *marinaClient) CreateTerminal(ctx context.Context, in *TerminalCreateRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/marina.Marina/CreateTerminal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarinaServer is the server API for Marina service.
// All implementations must embed UnimplementedMarinaServer
// for forward compatibility
type MarinaServer interface {
	CreateTerminal(context.Context, *TerminalCreateRequest) (*empty.Empty, error)
	mustEmbedUnimplementedMarinaServer()
}

// UnimplementedMarinaServer must be embedded to have forward compatible implementations.
type UnimplementedMarinaServer struct {
}

func (UnimplementedMarinaServer) CreateTerminal(context.Context, *TerminalCreateRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTerminal not implemented")
}
func (UnimplementedMarinaServer) mustEmbedUnimplementedMarinaServer() {}

// UnsafeMarinaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarinaServer will
// result in compilation errors.
type UnsafeMarinaServer interface {
	mustEmbedUnimplementedMarinaServer()
}

func RegisterMarinaServer(s grpc.ServiceRegistrar, srv MarinaServer) {
	s.RegisterService(&Marina_ServiceDesc, srv)
}

func _Marina_CreateTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminalCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarinaServer).CreateTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/marina.Marina/CreateTerminal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarinaServer).CreateTerminal(ctx, req.(*TerminalCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Marina_ServiceDesc is the grpc.ServiceDesc for Marina service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Marina_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marina.Marina",
	HandlerType: (*MarinaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTerminal",
			Handler:    _Marina_CreateTerminal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apis/marina.proto",
}
