apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "marina.fullname" . }}-gateway
  labels:
    {{- include "marina.gateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.gateway.autoscaling.enabled }}
  replicas: {{ .Values.gateway.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "marina.gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.gateway.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "marina.gateway.labels" . | nindent 8 }}
        {{- include "marina.gateway.selectorLabels" . | nindent 8 }}
        {{- with .Values.gateway.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.gateway.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "marina.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.gateway.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-gateway
          env:
          - name: MARINA_GATEWAY_PORT
            value: "{{ .Values.gateway.service.port }}" 
          securityContext:
            {{- toYaml .Values.gateway.securityContext | nindent 12 }}
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.gateway.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.gateway.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.gateway.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
          {{- with .Values.gateway.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          # todo: support new namespaces, etc
          command: ["/gateway"]
          args:
          {{- range .Values.terminal.images.blocked }}
          - "--block-image"
          - {{ include "toReference" . }}
          {{ end }}
          {{- range .Values.terminal.images.allowed -}}
          - "--allow-image"
          - {{ include "toReference" . }}
          {{- end -}}
      {{- with .Values.gateway.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
