apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "marina.name" . }}-gateway
  labels:
    {{- include "marina.labels" . | nindent 4 }}
rules:
- apiGroups: ["core.marina.io"]
  resources: ["users", "terminals"]
  verbs: ["create", "delete", "get", "list", "update", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "delete", "create"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["create", "delete", "get"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "marina.name" . }}-gateway
  labels:
	{{- include "marina.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "marina.name" . }}-gateway
subjects:
- kind: ServiceAccount
  name: {{ include "marina.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}