apiVersion: v1
kind: Service
metadata:
  name: {{ include "marina.fullname" . }}-gateway
  labels:
    {{- include "marina.gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
      name: grpc
  selector:
    {{- include "marina.gateway.selectorLabels" . | nindent 4 }}
