apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "marina.name" . }}-gateway
  labels:
    {{- include "marina.labels" . | nindent 4 }}
rules:
- apiGroups: ["core.marina.io"]
  resources: ["users", "terminals"]
  verbs: ["create", "delete", "get", "list", "update", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "delete", "create"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["create", "delete", "get"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "marina.name" . }}-gateway
  labels:
	{{- include "marina.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "marina.name" . }}-gateway
subjects:
- kind: ServiceAccount
  name: {{ include "marina.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "marina.name" . }}-operator
rules:
- apiGroups:
  - '*'
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.marina.io
  resources:
  - terminals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.marina.io
  resources:
  - terminals/finalizers
  verbs:
  - update
- apiGroups:
  - core.marina.io
  resources:
  - terminals/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.marina.io
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.marina.io
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - core.marina.io
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "marina.name" . }}-operator
  labels:
	{{- include "marina.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "marina.name" . }}-operator
subjects:
- kind: ServiceAccount
  name: {{ include "marina.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}